// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $admin_codes from "./routes/admin/codes.tsx";
import * as $admin_index from "./routes/admin/index.tsx";
import * as $admin_orders from "./routes/admin/orders.tsx";
import * as $api_admin_accept_order from "./routes/api/admin_accept_order.ts";
import * as $api_admin_create_code from "./routes/api/admin_create_code.ts";
import * as $api_admin_list_codes from "./routes/api/admin_list_codes.ts";
import * as $api_admin_list_orders from "./routes/api/admin_list_orders.ts";
import * as $api_admin_reject_order from "./routes/api/admin_reject_order.ts";
import * as $api_admin_remove_code from "./routes/api/admin_remove_code.ts";
import * as $api_get_article from "./routes/api/get_article.ts";
import * as $api_get_articles_form_source_ids from "./routes/api/get_articles_form_source_ids.ts";
import * as $api_get_order from "./routes/api/get_order.ts";
import * as $api_get_orders from "./routes/api/get_orders.ts";
import * as $api_order_media_mention from "./routes/api/order_media_mention.ts";
import * as $blog_urlid_ from "./routes/blog/[urlid].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $media_mentions from "./routes/media_mentions.tsx";
import * as $orders_order_id_ from "./routes/orders/[order_id].tsx";
import * as $orders_index from "./routes/orders/index.tsx";
import * as $polityka_prywatnosci from "./routes/polityka-prywatnosci.tsx";
import * as $random_order from "./routes/random-order.tsx";
import * as $regulamin from "./routes/regulamin.tsx";
import * as $AdminCodesPage from "./islands/AdminCodesPage.tsx";
import * as $AdminIndexPage from "./islands/AdminIndexPage.tsx";
import * as $AdminOrdersPage from "./islands/AdminOrdersPage.tsx";
import * as $ArticlePage from "./islands/ArticlePage.tsx";
import * as $LoadingScreen from "./islands/LoadingScreen.tsx";
import * as $MediaMentionsMakeOrderPanel from "./islands/MediaMentionsMakeOrderPanel.tsx";
import * as $MyOrdersPage from "./islands/MyOrdersPage.tsx";
import * as $OrderPage from "./islands/OrderPage.tsx";
import * as $SplashScreen from "./islands/SplashScreen.tsx";
import * as $TopNav from "./islands/TopNav.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/admin/codes.tsx": $admin_codes,
    "./routes/admin/index.tsx": $admin_index,
    "./routes/admin/orders.tsx": $admin_orders,
    "./routes/api/admin_accept_order.ts": $api_admin_accept_order,
    "./routes/api/admin_create_code.ts": $api_admin_create_code,
    "./routes/api/admin_list_codes.ts": $api_admin_list_codes,
    "./routes/api/admin_list_orders.ts": $api_admin_list_orders,
    "./routes/api/admin_reject_order.ts": $api_admin_reject_order,
    "./routes/api/admin_remove_code.ts": $api_admin_remove_code,
    "./routes/api/get_article.ts": $api_get_article,
    "./routes/api/get_articles_form_source_ids.ts":
      $api_get_articles_form_source_ids,
    "./routes/api/get_order.ts": $api_get_order,
    "./routes/api/get_orders.ts": $api_get_orders,
    "./routes/api/order_media_mention.ts": $api_order_media_mention,
    "./routes/blog/[urlid].tsx": $blog_urlid_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/index.tsx": $index,
    "./routes/media_mentions.tsx": $media_mentions,
    "./routes/orders/[order_id].tsx": $orders_order_id_,
    "./routes/orders/index.tsx": $orders_index,
    "./routes/polityka-prywatnosci.tsx": $polityka_prywatnosci,
    "./routes/random-order.tsx": $random_order,
    "./routes/regulamin.tsx": $regulamin,
  },
  islands: {
    "./islands/AdminCodesPage.tsx": $AdminCodesPage,
    "./islands/AdminIndexPage.tsx": $AdminIndexPage,
    "./islands/AdminOrdersPage.tsx": $AdminOrdersPage,
    "./islands/ArticlePage.tsx": $ArticlePage,
    "./islands/LoadingScreen.tsx": $LoadingScreen,
    "./islands/MediaMentionsMakeOrderPanel.tsx": $MediaMentionsMakeOrderPanel,
    "./islands/MyOrdersPage.tsx": $MyOrdersPage,
    "./islands/OrderPage.tsx": $OrderPage,
    "./islands/SplashScreen.tsx": $SplashScreen,
    "./islands/TopNav.tsx": $TopNav,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
